import {
  IconDefinition,
  faMicrochip,
  faShield,
  faBurst,
  faCirclePlus,
  faTag,
  faBolt,
  faExplosion,
  faPersonFallingBurst,
  faFireExtinguisher,
  faWrench,
  faSatelliteDish,
  faExpand,
  faRunning,
  faHandcuffs,
  faPlusCircle,
  faIdCard,
  faBriefcase,
  faCarBurst,
  faBullseye,
  faPersonRunning,
  faCube,
  faCircleRadiation,
  faHeart,
  faScaleBalanced,
  faCubesStacked,
  faCrosshairs,
  faScrewdriverWrench,
  faNetworkWired,
  faHandFist,
  faStairs,
} from "@fortawesome/free-solid-svg-icons";
import { BonusId } from "../schemas/lancerData/bonusId.schema";

type MoreIcons = "hull" | "agility" | "systems" | "engineering" | "tier";

export const ICONS: Record<BonusId | MoreIcons, IconDefinition> = {
  ai_cap: faMicrochip,
  armor: faShield,
  attack: faBurst,
  cb_point: faCirclePlus,
  cheap_stress: faTag,
  cheap_struct: faTag,
  core_power: faBolt,
  damage: faExplosion,
  deployable_armor: faShield,
  deployable_charges: faCirclePlus,
  deployable_edef: faMicrochip,
  deployable_evasion: faPersonFallingBurst,
  deployable_heatcap: faFireExtinguisher,
  deployable_hp: faHeart,
  deployable_repcap: faWrench,
  deployable_save: faCirclePlus,
  deployable_sensor_range: faSatelliteDish,
  deployable_size: faExpand,
  deployable_speed: faRunning,
  deployable_tech_attack: faBolt,
  drone_armor: faShield,
  drone_charges: faCirclePlus,
  drone_edef: faMicrochip,
  drone_evasion: faPersonFallingBurst,
  drone_heatcap: faFireExtinguisher,
  drone_hp: faHeart,
  drone_repcap: faWrench,
  drone_save: faCirclePlus,
  drone_sensor_range: faSatelliteDish,
  drone_size: faExpand,
  drone_speed: faRunning,
  drone_tech_attack: faBolt,
  edef: faMicrochip,
  evasion: faPersonFallingBurst,
  grapple: faHandcuffs,
  heatcap: faFireExtinguisher,
  hp: faHeart,
  license_point: faIdCard,
  limited_bonus: faPlusCircle,
  mech_skill_point: faPlusCircle,
  overcharge: faBolt,
  pilot_armor: faShield,
  pilot_edef: faMicrochip,
  pilot_evasion: faPersonFallingBurst,
  pilot_gear: faBriefcase,
  pilot_hp: faHeart,
  pilot_speed: faRunning,
  ram: faCarBurst,
  range: faCrosshairs,
  repcap: faWrench,
  save: faScaleBalanced,
  sensor: faSatelliteDish,
  size: faExpand,
  skill_point: faCirclePlus,
  sp: faCirclePlus,
  speed: faPersonRunning,
  stress: faCircleRadiation,
  structure: faCube,
  talent_point: faCirclePlus,
  tech_attack: faBolt,
  activations: faCubesStacked,
  evade: faPersonFallingBurst,
  sizes: faExpand,
  hull: faHandFist,
  agility: faPersonRunning,
  systems: faNetworkWired,
  engineering: faScrewdriverWrench,
  tier: faStairs,
};
